### ISSUE TITLE
MDM master failover

### ISSUE THREAD

**Issue by getstek** [sperreault/ansible-scaleio#5]
Hi,

I am having a slight issue with the playbook, running it against CentOS7 with the latest version of ScaleIO. The install hangs at the SDS role, it appears to have an issue when connecting to the mdm_master.

In the playbook this is the first server under the [mdm] section, however once the primary MDM stage is completed and the secondary MDM is added, the IP address seems to failover to the secondary MDM and causes login to fail in the SDS role. As a workaround, I tried the following:

```
- set_fact: role_name=sds

- include: ../../install_scaleio.yml

- name: find disks
  disk_facts:
  register: disks

- name: use local disk variable
  when: sds_scaleio_disks
  set_fact: disks="{{ sds_scaleio_disks }}"

- name: login to mdm
  command: scli --mdm_ip "{{ scaleio_mdm_headnode_ip }},{{ scaleio_mdm_secondary_ip }}" --login  --username admin --password "{{ scaleio_password }}"
  run_once: true
  delegate_to: "{{ scaleio_mdm_headnode_ip }}"
```

Where you can see the login I changed to have ip1,ip2 (I read on the EMC forum this was possible), yet it still seems to fail. Any ideas on how I could get the playbook to work with IP failover on the MDM?
